-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('INBOUND', 'OUTBOUND', 'MATERIAL', 'RETURNORDER', 'STOCK', 'SYSTEM') NOT NULL;

-- AlterTable
ALTER TABLE `StockHistory` MODIFY `type` ENUM('INBOUND', 'OUTBOUND', 'RETURNORDER', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUST') NOT NULL;
